# Generated by Django 4.0.5 on 2022-06-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_main',
        ),
        migrations.AddField(
            model_name='productimg',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
